# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Decode FASTQ
#'
#' Recover loxcodes from raw Illumina FASTQ output
#' @param r Paths of R1, 2 respectively
#' @param meta User-defined data-frame for sample metadata 
#' @return S4 loxcode_sample object with decoded results
#' @export
decode <- function(r, meta) {
    .Call(`_loxcoder_decode`, r, meta)
}

