# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert vector of cassette strings to list of numeric vectors 
#' 
#' @param c vector of cassette strings 
#' @export
get_cass_vec <- function(c) {
    .Call(`_loxcoder_get_cass_vec`, c)
}

#' Check if cassette is valid
#'
#' Checks that cassette is an allowed size, even and odd elements are well-positioned
#' and that there are no repeated elements. 
#' @param c a list of numeric vectors, or a character vector of decoded loxcodes 
#' @return TRUE if the cassette is valid, otherwise FALSE 
#' @export
is_valid <- function(c) {
    .Call(`_loxcoder_is_valid`, c)
}

#' Decode FASTQ
#'
#' Recover loxcodes from raw Illumina FASTQ output
#' @param r Paths of R1, 2 respectively
#' @param meta User-defined data-frame for sample metadata
#' @param min_read_length min read length for R1, R2 filter respectively
#' @return S4 loxcode_sample object with decoded results
#' @export
decode <- function(r, meta, min_r1_len = 354L, min_r2_len = 244L) {
    .Call(`_loxcoder_decode`, r, meta, min_r1_len, min_r2_len)
}

