# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert vector of cassette strings to list of numeric vectors 
#' 
#' @param c vector of cassette strings 
#' @export
get_cass_vec <- function(c) {
    .Call(`_loxcoder_get_cass_vec`, c)
}

#' Check if cassette is valid
#'
#' Checks that cassette is an allowed size, even and odd elements are well-positioned
#' and that there are no repeated elements. 
#' @param c a list of numeric vectors, or a character vector of decoded loxcodes 
#' @return TRUE if the cassette is valid, otherwise FALSE 
#' @export
is_valid <- function(c) {
    .Call(`_loxcoder_is_valid`, c)
}

#' Impute missing element in a 13-element cassette
#' @export
impute_13_impl <- function(c2) {
    .Call(`_loxcoder_impute_13_impl`, c2)
}

#' Impute missing elements
#' @export
impute_13 <- function(c, sizes) {
    .Call(`_loxcoder_impute_13`, c, sizes)
}

#' Decode FASTQ
#'
#' Recover loxcodes from raw Illumina FASTQ output
#' @param r Paths of R1, 2 respectively
#' @param meta User-defined data-frame for sample metadata
#' @param min_read_length min read length for R1, R2 filter respectively
#' @return S4 loxcode_sample object with decoded results
#' @export
decode <- function(r, name, meta, min_r1_len, min_r2_len) {
    .Call(`_loxcoder_decode`, r, name, meta, min_r1_len, min_r2_len)
}

load_origin_files_wrapper <- function(paths) {
    invisible(.Call(`_loxcoder_load_origin_files_wrapper`, paths))
}

load_pair_files_wrapper <- function(paths) {
    invisible(.Call(`_loxcoder_load_pair_files_wrapper`, paths))
}

wrapper_fill_tables <- function() {
    invisible(.Call(`_loxcoder_wrapper_fill_tables`))
}

#' Pack cassettes into cassette ID
#'
#' @param c a list of numeric vectors, or a character vector of decoded loxcodes
#' @param v vector of bool, output from validate()
#' @export
pack <- function(c, v) {
    .Call(`_loxcoder_pack`, c, v)
}

#' @export
retrieve_dist_origin <- function(c, sizes) {
    .Call(`_loxcoder_retrieve_dist_origin`, c, sizes)
}

#' @export
retrieve_dist_pair <- function(c1, c2, size) {
    .Call(`_loxcoder_retrieve_dist_pair`, c1, c2, size)
}

